# Generated by Django 3.0.4 on 2020-05-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoTiposProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asociado',
            name='fechanac',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoTiposProyecto'),
        ),
    ]
