# Generated by Django 3.0.4 on 2020-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0002_auto_20200526_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.IntegerField(),
        ),
    ]
