# Generated by Django 3.0.4 on 2020-05-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0003_auto_20200526_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoTiposProyecto'),
        ),
    ]
