# Generated by Django 3.0.4 on 2020-05-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0006_asociado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado'),
        ),
    ]
