# Generated by Django 3.0.4 on 2020-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0007_auto_20200526_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0, max_length=2),
        ),
    ]
