# Generated by Django 3.0.4 on 2020-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0008_asociado_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0),
        ),
    ]
