# Generated by Django 3.0.4 on 2020-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0010_auto_20200530_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
