# Generated by Django 3.0.4 on 2020-05-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0012_catalogoredessociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsocRedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('redsocial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoRedesSociales')),
            ],
        ),
    ]
