# Generated by Django 3.0.4 on 2020-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0013_auto_20200531_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoTiposProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asocredessociales',
            options={'verbose_name': 'Redes Sociales por Asociado'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyectos por Asociado'},
        ),
    ]
