# Generated by Django 3.0.4 on 2020-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0014_auto_20200531_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='asocredessociales',
            name='link',
            field=models.URLField(default='no capturada', max_length=30),
        ),
    ]
