# Generated by Django 3.0.4 on 2020-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0015_asocredessociales_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asocredessociales',
            name='link',
            field=models.URLField(default='no capturada', max_length=100),
        ),
    ]
