# Generated by Django 3.0.4 on 2020-06-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0016_auto_20200531_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDocumentosAcademicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo de Documentos Academicos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Catalogo de Empresas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoGradosAcademicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo de Grados Academicos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoHabilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo Habilidades Personales',
            },
        ),
        migrations.CreateModel(
            name='CatalogoIdiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo de Idiomas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoInstitucionesEducativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Catalogo de Instituciones Educativas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoLenguajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo de Lenguajes de Programacion',
            },
        ),
        migrations.CreateModel(
            name='CatalogoPuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catalogo de Puestos de Trabajo',
            },
        ),
        migrations.AlterModelOptions(
            name='asociado',
            options={'verbose_name': 'Asociado'},
        ),
        migrations.AddField(
            model_name='asociado',
            name='intereses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HabilidadesLenguajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoLenguajes')),
            ],
            options={
                'verbose_name': 'Lenguajes de Programacion por Asociado',
            },
        ),
        migrations.CreateModel(
            name='HabilidadesIdiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoIdiomas')),
            ],
            options={
                'verbose_name': 'Idiomas por Asociado',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoHabilidades')),
            ],
            options={
                'verbose_name': 'Habilidades por Asociado',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoEmpresas')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoPuestos')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral por Asociado',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoDocumentosAcademicos')),
                ('gradoacademico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoGradosAcademicos')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.CatalogoInstitucionesEducativas')),
            ],
            options={
                'verbose_name': 'Educacion por Asociado',
            },
        ),
        migrations.CreateModel(
            name='CursosCapacitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField()),
                ('anio', models.SmallIntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAsociados.Asociado')),
            ],
            options={
                'verbose_name': 'Cursos y Capacitaciones por Asociado',
            },
        ),
    ]
