# Generated by Django 3.0.4 on 2020-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0017_auto_20200606_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogodocumentosacademicos',
            options={'verbose_name': 'Catalogo de Documentos Academico'},
        ),
        migrations.AlterModelOptions(
            name='catalogogradosacademicos',
            options={'verbose_name': 'Catalogo de Grados Academico'},
        ),
        migrations.AlterModelOptions(
            name='catalogohabilidades',
            options={'verbose_name': 'Catalogo Habilidades Personale'},
        ),
        migrations.AlterModelOptions(
            name='catalogoidiomas',
            options={'verbose_name': 'Catalogo de Idioma'},
        ),
        migrations.AlterModelOptions(
            name='catalogoinstitucioneseducativas',
            options={'verbose_name': 'Catalogo de Instituciones Educativa'},
        ),
        migrations.AlterModelOptions(
            name='catalogoredessociales',
            options={'verbose_name': 'Catalogo de Redes Sociale'},
        ),
        migrations.AlterModelOptions(
            name='catalogotiposproyecto',
            options={'verbose_name': 'Catalogo de Tipos de Proyecto'},
        ),
        migrations.AddField(
            model_name='educacion',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoinstitucioneseducativas',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
