# Generated by Django 3.0.4 on 2020-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0018_auto_20200606_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
