# Generated by Django 3.0.4 on 2020-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0019_auto_20200606_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-fechainicio'], 'verbose_name': 'Educacion por Asociado'},
        ),
        migrations.AddField(
            model_name='catalogoidiomas',
            name='icono',
            field=models.ImageField(default=0, upload_to='idiomas/'),
            preserve_default=False,
        ),
    ]
