# Generated by Django 3.0.4 on 2020-06-06 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0020_auto_20200606_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogohabilidades',
            options={'verbose_name': 'Catalogo Habilidades Personales'},
        ),
        migrations.AlterField(
            model_name='catalogoidiomas',
            name='icono',
            field=models.FileField(upload_to='idiomas/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
