# Generated by Django 3.0.4 on 2020-06-07 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0022_catalogolenguajes_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogotiposproyecto',
            name='icono',
            field=models.FileField(default=0, upload_to='tiposproyecto/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
            preserve_default=False,
        ),
    ]
