# Generated by Django 3.0.4 on 2020-06-07 19:47

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0024_asociado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contenido',
            field=tinymce.models.HTMLField(default='capturar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asociado',
            name='foto',
            field=models.FileField(upload_to='fotosasociados/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])]),
        ),
    ]
